name: Merge Outputs Workflow

on: push

jobs:
  vulnerability_scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [image1, image2, image3]

    outputs:
      high_vulnerabilities: ${{ steps.check_vulnerabilities.outputs.high_vulnerabilities }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Scan Docker image
      run: |
        echo ${{ matrix.image }}

    - name: Check for vulnerabilities
      id: check_vulnerabilities
      run: |
        if [ "${{ matrix.image }}" == "image2" ]; then
          echo "::set-output name=high_vulnerabilities::true"
        else
          echo "::set-output name=high_vulnerabilities::false"
        fi

  merge_outputs:
    needs: vulnerability_scan
    runs-on: ubuntu-latest

    steps:
    - name: Merge outputs
      id: merge_outputs
      if: ${{ needs.vulnerability_scan.outputs.high_vulnerabilities == "true" }}
      run: |
        echo "High vulnerabilities:"
        echo "${{ needs.vulnerability_scan.outputs.high_vulnerabilities }}"